services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: .env
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data:
